Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cf10cdf9fcd62d37
      Tags:
        - Key: "Name"
          Value: !Join ["_",[My, Instance, From, Cloudformation]]