Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0cf10cdf9fcd62d37
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "MyInstance"
              - !Ref AWS::Region
            
      SecurityGroups:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and http to client host
      
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 103.225.244.10/32

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 103.225.244.10/32
